//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/MessageModel.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/MessageModel.xsd", IsNullable=false)]
public partial class MessageModel {
    
    private int packageStartField;
    
    private int wiFiControlField;
    
    private int throttleField;
    
    private int rudderField;
    
    private int elevatorField;
    
    private int aileronField;
    
    private int gyroField;
    
    private int checksumField;
    
    private int packageEndField;
    
    /// <remarks/>
    public int PackageStart {
        get {
            return this.packageStartField;
        }
        set {
            this.packageStartField = value;
        }
    }
    
    /// <remarks/>
    public int WiFiControl {
        get {
            return this.wiFiControlField;
        }
        set {
            this.wiFiControlField = value;
        }
    }
    
    /// <remarks/>
    public int Throttle {
        get {
            return this.throttleField;
        }
        set {
            this.throttleField = value;
        }
    }
    
    /// <remarks/>
    public int Rudder {
        get {
            return this.rudderField;
        }
        set {
            this.rudderField = value;
        }
    }
    
    /// <remarks/>
    public int Elevator {
        get {
            return this.elevatorField;
        }
        set {
            this.elevatorField = value;
        }
    }
    
    /// <remarks/>
    public int Aileron {
        get {
            return this.aileronField;
        }
        set {
            this.aileronField = value;
        }
    }
    
    /// <remarks/>
    public int Gyro {
        get {
            return this.gyroField;
        }
        set {
            this.gyroField = value;
        }
    }
    
    /// <remarks/>
    public int Checksum {
        get {
            return this.checksumField;
        }
        set {
            this.checksumField = value;
        }
    }
    
    /// <remarks/>
    public int PackageEnd {
        get {
            return this.packageEndField;
        }
        set {
            this.packageEndField = value;
        }
    }
}
